# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ecrpc/external_coordinator.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'ecrpc/external_coordinator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ecrpc/external_coordinator.proto\x12\x05\x65\x63rpc\x1a\x1cgoogle/api/annotations.proto\"I\n\x1dRegisterMissionControlRequest\x12(\n\x05pairs\x18\x01 \x03(\x0b\x32\x12.ecrpc.PairHistoryR\x05pairs\"I\n\x1eRegisterMissionControlResponse\x12\'\n\x0fsuccess_message\x18\x01 \x01(\tR\x0esuccessMessage\"&\n$QueryAggregatedMissionControlRequest\"Q\n%QueryAggregatedMissionControlResponse\x12(\n\x05pairs\x18\x01 \x03(\x0b\x32\x12.ecrpc.PairHistoryR\x05pairs\"n\n\x0bPairHistory\x12\x1b\n\tnode_from\x18\x01 \x01(\x0cR\x08nodeFrom\x12\x17\n\x07node_to\x18\x02 \x01(\x0cR\x06nodeTo\x12)\n\x07history\x18\x03 \x01(\x0b\x32\x0f.ecrpc.PairDataR\x07history\"\xe2\x01\n\x08PairData\x12\x1b\n\tfail_time\x18\x01 \x01(\x03R\x08\x66\x61ilTime\x12 \n\x0c\x66\x61il_amt_sat\x18\x02 \x01(\x03R\nfailAmtSat\x12\"\n\rfail_amt_msat\x18\x03 \x01(\x03R\x0b\x66\x61ilAmtMsat\x12!\n\x0csuccess_time\x18\x04 \x01(\x03R\x0bsuccessTime\x12&\n\x0fsuccess_amt_sat\x18\x05 \x01(\x03R\rsuccessAmtSat\x12(\n\x10success_amt_msat\x18\x06 \x01(\x03R\x0esuccessAmtMsat2\xce\x02\n\x13\x45xternalCoordinator\x12\x8c\x01\n\x16RegisterMissionControl\x12$.ecrpc.RegisterMissionControlRequest\x1a%.ecrpc.RegisterMissionControlResponse\"%\x82\xd3\xe4\x93\x02\x1f\"\x1a/v1/registermissioncontrol:\x01*\x12\xa7\x01\n\x1dQueryAggregatedMissionControl\x12+.ecrpc.QueryAggregatedMissionControlRequest\x1a,.ecrpc.QueryAggregatedMissionControlResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/queryaggregatedmissioncontrol0\x01\x42\x41Z?github.com/ziggie1984/Distributed-Mission-Control-for-LND/ecrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ecrpc.external_coordinator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z?github.com/ziggie1984/Distributed-Mission-Control-for-LND/ecrpc'
  _globals['_EXTERNALCOORDINATOR'].methods_by_name['RegisterMissionControl']._loaded_options = None
  _globals['_EXTERNALCOORDINATOR'].methods_by_name['RegisterMissionControl']._serialized_options = b'\202\323\344\223\002\037\"\032/v1/registermissioncontrol:\001*'
  _globals['_EXTERNALCOORDINATOR'].methods_by_name['QueryAggregatedMissionControl']._loaded_options = None
  _globals['_EXTERNALCOORDINATOR'].methods_by_name['QueryAggregatedMissionControl']._serialized_options = b'\202\323\344\223\002#\022!/v1/queryaggregatedmissioncontrol'
  _globals['_REGISTERMISSIONCONTROLREQUEST']._serialized_start=73
  _globals['_REGISTERMISSIONCONTROLREQUEST']._serialized_end=146
  _globals['_REGISTERMISSIONCONTROLRESPONSE']._serialized_start=148
  _globals['_REGISTERMISSIONCONTROLRESPONSE']._serialized_end=221
  _globals['_QUERYAGGREGATEDMISSIONCONTROLREQUEST']._serialized_start=223
  _globals['_QUERYAGGREGATEDMISSIONCONTROLREQUEST']._serialized_end=261
  _globals['_QUERYAGGREGATEDMISSIONCONTROLRESPONSE']._serialized_start=263
  _globals['_QUERYAGGREGATEDMISSIONCONTROLRESPONSE']._serialized_end=344
  _globals['_PAIRHISTORY']._serialized_start=346
  _globals['_PAIRHISTORY']._serialized_end=456
  _globals['_PAIRDATA']._serialized_start=459
  _globals['_PAIRDATA']._serialized_end=685
  _globals['_EXTERNALCOORDINATOR']._serialized_start=688
  _globals['_EXTERNALCOORDINATOR']._serialized_end=1022
# @@protoc_insertion_point(module_scope)
