# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ecrpc import external_coordinator_pb2 as ecrpc_dot_external__coordinator__pb2


class ExternalCoordinatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterMissionControl = channel.unary_unary(
                '/ecrpc.ExternalCoordinator/RegisterMissionControl',
                request_serializer=ecrpc_dot_external__coordinator__pb2.RegisterMissionControlRequest.SerializeToString,
                response_deserializer=ecrpc_dot_external__coordinator__pb2.RegisterMissionControlResponse.FromString,
                _registered_method=True)
        self.QueryAggregatedMissionControl = channel.unary_stream(
                '/ecrpc.ExternalCoordinator/QueryAggregatedMissionControl',
                request_serializer=ecrpc_dot_external__coordinator__pb2.QueryAggregatedMissionControlRequest.SerializeToString,
                response_deserializer=ecrpc_dot_external__coordinator__pb2.QueryAggregatedMissionControlResponse.FromString,
                _registered_method=True)


class ExternalCoordinatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterMissionControl(self, request, context):
        """RegisterMissionControl registers mission control data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAggregatedMissionControl(self, request, context):
        """QueryAggregatedMissionControl queries aggregated mission control data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExternalCoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterMissionControl': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterMissionControl,
                    request_deserializer=ecrpc_dot_external__coordinator__pb2.RegisterMissionControlRequest.FromString,
                    response_serializer=ecrpc_dot_external__coordinator__pb2.RegisterMissionControlResponse.SerializeToString,
            ),
            'QueryAggregatedMissionControl': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryAggregatedMissionControl,
                    request_deserializer=ecrpc_dot_external__coordinator__pb2.QueryAggregatedMissionControlRequest.FromString,
                    response_serializer=ecrpc_dot_external__coordinator__pb2.QueryAggregatedMissionControlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ecrpc.ExternalCoordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ecrpc.ExternalCoordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExternalCoordinator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterMissionControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecrpc.ExternalCoordinator/RegisterMissionControl',
            ecrpc_dot_external__coordinator__pb2.RegisterMissionControlRequest.SerializeToString,
            ecrpc_dot_external__coordinator__pb2.RegisterMissionControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryAggregatedMissionControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ecrpc.ExternalCoordinator/QueryAggregatedMissionControl',
            ecrpc_dot_external__coordinator__pb2.QueryAggregatedMissionControlRequest.SerializeToString,
            ecrpc_dot_external__coordinator__pb2.QueryAggregatedMissionControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
